/* cmsis_shim.h — EmberSim CMSIS macro compatibility shim
* Generated by 'embersim init --repair'.
* These stubs emit runtime warnings. Replace with mock_* API calls in production.
*/

#ifndef CMSIS_SHIM_H
#define CMSIS_SHIM_H

#include <stdio.h>

#define EMBER_SIM_WARN_MACRO(name) \
    fprintf(stderr, "EMBERSIM: HAL macro '%s' not simulated. Replace with mock_* API.\n", name)

#ifndef __HAL_TIM_SET_AUTORELOAD
#define __HAL_TIM_SET_AUTORELOAD(...) \
    EMBER_SIM_WARN_MACRO("__HAL_TIM_SET_AUTORELOAD")
#endif

#endif /* CMSIS_SHIM_H */
